//! Regenerates `src/builtins/names.rs` from the upstream Scarpet reference and
//! fails if the checked-in file is stale. On a mismatch the file is rewritten in
//! place — re-run the test and commit the result.
//!
//! The reference lives in the `example/` submodule, which most CI legs do not
//! check out, so this runs as a *test* and the generated file is committed —
//! the same arrangement as `scarpet-syntax`'s node generator. A build script
//! would hard-fail every job that skips submodules, including the playground
//! deploy. When the submodule is absent the test skips quietly, which means a
//! green `cargo test` locally does not prove this ran.

use std::collections::BTreeSet;
use std::path::PathBuf;

/// The reference file, relative to the workspace root.
const REFERENCE: &str = "example/gnembon/fabric-carpet/docs/scarpet/Full.md";

#[test]
fn generated_builtin_names_are_current() {
    let crate_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let reference = crate_root.join("..").join(REFERENCE);
    let Ok(doc) = std::fs::read_to_string(&reference) else {
        eprintln!(
            "skipping builtin-name sourcegen: {} absent (run `git submodule update --init`)",
            reference.display()
        );
        return;
    };

    let generated = rustfmt(&render(&extract(&doc)));
    let path = crate_root.join("src/builtins/names.rs");
    let on_disk = std::fs::read_to_string(&path).unwrap_or_default();
    if normalize(&on_disk) != normalize(&generated) {
        std::fs::write(&path, &generated).expect("write names.rs");
        panic!(
            "{} was stale and has been regenerated — re-run the test and commit it",
            path.display()
        );
    }
}

fn normalize(s: &str) -> String {
    s.replace("\r\n", "\n").trim_end().to_string()
}

/// Pipe through `rustfmt` so the emitted file satisfies `cargo fmt --check`.
fn rustfmt(text: &str) -> String {
    use std::io::Write as _;
    use std::process::{Command, Stdio};
    let mut child = Command::new("rustfmt")
        .args(["--edition", "2024"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .expect("spawn rustfmt (rustup component add rustfmt)");
    child
        .stdin
        .take()
        .expect("rustfmt stdin")
        .write_all(text.as_bytes())
        .expect("write to rustfmt");
    let out = child.wait_with_output().expect("run rustfmt");
    assert!(out.status.success(), "rustfmt rejected the generated code");
    String::from_utf8(out.stdout).expect("rustfmt output is UTF-8")
}

/// Every function name the reference documents.
///
/// Its `###` headings hold the signatures, sometimes several to a line and
/// sometimes mixed with prose:
///
/// ```text
/// ### `min(arg, ...), min(list), max(arg, ...), max(list)`
/// ### Logical Operators `&&`, `and(...)`, `||`, `or(...)`
/// ### `Assignment Operators = <> +=`
/// ```
///
/// So: inside each backtick-delimited span, take every identifier that is
/// immediately followed by `(` **at bracket depth zero**. The depth check is
/// what keeps parameter names out — `min(list)` must yield `min`, not `list`.
fn extract(doc: &str) -> BTreeSet<String> {
    let mut names = BTreeSet::new();
    for line in doc.lines() {
        let Some(heading) = line.strip_prefix("### ") else {
            continue;
        };
        // Odd-indexed pieces of a backtick split are the code spans.
        for span in heading.split('`').skip(1).step_by(2) {
            collect_calls(span, &mut names);
        }
    }
    names
}

fn collect_calls(span: &str, names: &mut BTreeSet<String>) {
    let bytes = span.as_bytes();
    let mut depth = 0usize;
    let mut i = 0;
    while i < bytes.len() {
        if depth == 0 && is_ident_start(bytes[i]) {
            let start = i;
            while i < bytes.len() && is_ident_continue(bytes[i]) {
                i += 1;
            }
            if bytes.get(i) == Some(&b'(') {
                names.insert(span[start..i].to_owned());
            }
            continue;
        }
        match bytes[i] {
            b'(' => depth += 1,
            b')' => depth = depth.saturating_sub(1),
            _ => {}
        }
        i += 1;
    }
}

fn is_ident_start(b: u8) -> bool {
    b.is_ascii_alphabetic() || b == b'_'
}

fn is_ident_continue(b: u8) -> bool {
    b.is_ascii_alphanumeric() || b == b'_'
}

fn render(names: &BTreeSet<String>) -> String {
    let mut out = String::new();
    out.push_str(
        "//! Generated by `tests/sourcegen.rs` from the upstream Scarpet reference — do\n\
         //! not edit.\n\
         \n\
         /// Every function name `docs/scarpet/Full.md` documents, sorted for\n\
         /// `binary_search`.\n\
         ///\n\
         /// Names only: the reference records signatures like `min(arg, ...)` but no\n\
         /// types, so this list can answer \"does this function exist\" and nothing more.\n\
         /// Anything with a return type is hand-written in [`super::builtin`].\n\
         pub(super) static BUILTIN_NAMES: &[&str] = &[\n",
    );
    for name in names {
        out.push_str("    \"");
        out.push_str(name);
        out.push_str("\",\n");
    }
    out.push_str("];\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The depth rule is the whole trick; a parameter name must never be
    /// mistaken for a function.
    #[test]
    fn only_top_level_calls_are_collected() {
        let doc = "### `min(arg, ...), min(list), max(list)`\n\
                   ### Logical Operators `&&`, `and(...)`, `||`, `or(...)`\n\
                   ### `Assignment Operators = <> +=`\n\
                   not a heading `nope()`\n";
        let names: Vec<String> = extract(doc).into_iter().collect();
        assert_eq!(names, ["and", "max", "min", "or"]);
    }

    #[test]
    fn nested_calls_in_a_parameter_are_not_functions() {
        // `for(list,expr(_,_i))` documents `for`; `expr` is a parameter.
        let names: Vec<String> = extract("### `for(list,expr(_,_i))`\n")
            .into_iter()
            .collect();
        assert_eq!(names, ["for"]);
    }
}
