//! Generated by `tests/sourcegen.rs` from `scarpet.ungram` — do not edit.

use super::{AstChildren, AstNode, support};
use crate::syntax::{SyntaxKind, SyntaxNode, SyntaxToken};

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Root {
    syntax: SyntaxNode,
}

impl AstNode for Root {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::ROOT
    }

    fn cast(syntax: SyntaxNode) -> Option<Self> {
        Self::can_cast(syntax.kind()).then_some(Self { syntax })
    }

    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

impl Root {
    pub fn expr(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Expr {
    Literal(Literal),
    NameRef(NameRef),
    CallExpr(CallExpr),
    ListExpr(ListExpr),
    MapExpr(MapExpr),
    ParenExpr(ParenExpr),
    PrefixExpr(PrefixExpr),
    ArrowExpr(ArrowExpr),
    BinExpr(BinExpr),
}

impl AstNode for Expr {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(
            kind,
            SyntaxKind::LITERAL
                | SyntaxKind::NAME_REF
                | SyntaxKind::CALL_EXPR
                | SyntaxKind::LIST_EXPR
                | SyntaxKind::MAP_EXPR
                | SyntaxKind::PAREN_EXPR
                | SyntaxKind::PREFIX_EXPR
                | SyntaxKind::ARROW_EXPR
                | SyntaxKind::BIN_EXPR
        )
    }

    fn cast(syntax: SyntaxNode) -> Option<Self> {
        let node = match syntax.kind() {
            SyntaxKind::LITERAL => Expr::Literal(Literal { syntax }),
            SyntaxKind::NAME_REF => Expr::NameRef(NameRef { syntax }),
            SyntaxKind::CALL_EXPR => Expr::CallExpr(CallExpr { syntax }),
            SyntaxKind::LIST_EXPR => Expr::ListExpr(ListExpr { syntax }),
            SyntaxKind::MAP_EXPR => Expr::MapExpr(MapExpr { syntax }),
            SyntaxKind::PAREN_EXPR => Expr::ParenExpr(ParenExpr { syntax }),
            SyntaxKind::PREFIX_EXPR => Expr::PrefixExpr(PrefixExpr { syntax }),
            SyntaxKind::ARROW_EXPR => Expr::ArrowExpr(ArrowExpr { syntax }),
            SyntaxKind::BIN_EXPR => Expr::BinExpr(BinExpr { syntax }),
            _ => return None,
        };
        Some(node)
    }

    fn syntax(&self) -> &SyntaxNode {
        match self {
            Expr::Literal(it) => &it.syntax,
            Expr::NameRef(it) => &it.syntax,
            Expr::CallExpr(it) => &it.syntax,
            Expr::ListExpr(it) => &it.syntax,
            Expr::MapExpr(it) => &it.syntax,
            Expr::ParenExpr(it) => &it.syntax,
            Expr::PrefixExpr(it) => &it.syntax,
            Expr::ArrowExpr(it) => &it.syntax,
            Expr::BinExpr(it) => &it.syntax,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Literal {
    syntax: SyntaxNode,
}

impl AstNode for Literal {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::LITERAL
    }

    fn cast(syntax: SyntaxNode) -> Option<Self> {
        Self::can_cast(syntax.kind()).then_some(Self { syntax })
    }

    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

impl Literal {
    pub fn value_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, &[SyntaxKind::NUMBER, SyntaxKind::STRING])
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct NameRef {
    syntax: SyntaxNode,
}

impl AstNode for NameRef {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::NAME_REF
    }

    fn cast(syntax: SyntaxNode) -> Option<Self> {
        Self::can_cast(syntax.kind()).then_some(Self { syntax })
    }

    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

impl NameRef {
    pub fn ident_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, &[SyntaxKind::IDENT])
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct CallExpr {
    syntax: SyntaxNode,
}

impl AstNode for CallExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::CALL_EXPR
    }

    fn cast(syntax: SyntaxNode) -> Option<Self> {
        Self::can_cast(syntax.kind()).then_some(Self { syntax })
    }

    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

impl CallExpr {
    pub fn callee(&self) -> Option<NameRef> {
        support::child(&self.syntax)
    }

    pub fn arg_list(&self) -> Option<ArgList> {
        support::child(&self.syntax)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ListExpr {
    syntax: SyntaxNode,
}

impl AstNode for ListExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::LIST_EXPR
    }

    fn cast(syntax: SyntaxNode) -> Option<Self> {
        Self::can_cast(syntax.kind()).then_some(Self { syntax })
    }

    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

impl ListExpr {
    pub fn l_brack_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, &[SyntaxKind::L_BRACK])
    }

    pub fn args(&self) -> AstChildren<Expr> {
        support::children(&self.syntax)
    }

    pub fn r_brack_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, &[SyntaxKind::R_BRACK])
    }

    pub fn l_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, &[SyntaxKind::L_KW])
    }

    pub fn l_paren_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, &[SyntaxKind::L_PAREN])
    }

    pub fn r_paren_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, &[SyntaxKind::R_PAREN])
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct MapExpr {
    syntax: SyntaxNode,
}

impl AstNode for MapExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::MAP_EXPR
    }

    fn cast(syntax: SyntaxNode) -> Option<Self> {
        Self::can_cast(syntax.kind()).then_some(Self { syntax })
    }

    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

impl MapExpr {
    pub fn l_brace_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, &[SyntaxKind::L_BRACE])
    }

    pub fn args(&self) -> AstChildren<Expr> {
        support::children(&self.syntax)
    }

    pub fn r_brace_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, &[SyntaxKind::R_BRACE])
    }

    pub fn m_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, &[SyntaxKind::M_KW])
    }

    pub fn l_paren_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, &[SyntaxKind::L_PAREN])
    }

    pub fn r_paren_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, &[SyntaxKind::R_PAREN])
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ParenExpr {
    syntax: SyntaxNode,
}

impl AstNode for ParenExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::PAREN_EXPR
    }

    fn cast(syntax: SyntaxNode) -> Option<Self> {
        Self::can_cast(syntax.kind()).then_some(Self { syntax })
    }

    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

impl ParenExpr {
    pub fn l_paren_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, &[SyntaxKind::L_PAREN])
    }

    pub fn expr(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }

    pub fn r_paren_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, &[SyntaxKind::R_PAREN])
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct PrefixExpr {
    syntax: SyntaxNode,
}

impl AstNode for PrefixExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::PREFIX_EXPR
    }

    fn cast(syntax: SyntaxNode) -> Option<Self> {
        Self::can_cast(syntax.kind()).then_some(Self { syntax })
    }

    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

impl PrefixExpr {
    pub fn op_token(&self) -> Option<SyntaxToken> {
        support::token(
            &self.syntax,
            &[
                SyntaxKind::MINUS,
                SyntaxKind::PLUS,
                SyntaxKind::BANG,
                SyntaxKind::DOT3,
            ],
        )
    }

    pub fn expr(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ArrowExpr {
    syntax: SyntaxNode,
}

impl AstNode for ArrowExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::ARROW_EXPR
    }

    fn cast(syntax: SyntaxNode) -> Option<Self> {
        Self::can_cast(syntax.kind()).then_some(Self { syntax })
    }

    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

impl ArrowExpr {
    pub fn lhs(&self) -> Option<Expr> {
        support::nth_child(&self.syntax, 0)
    }

    pub fn arrow_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, &[SyntaxKind::ARROW])
    }

    pub fn rhs(&self) -> Option<Expr> {
        support::nth_child(&self.syntax, 1)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct BinExpr {
    syntax: SyntaxNode,
}

impl AstNode for BinExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::BIN_EXPR
    }

    fn cast(syntax: SyntaxNode) -> Option<Self> {
        Self::can_cast(syntax.kind()).then_some(Self { syntax })
    }

    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

impl BinExpr {
    pub fn lhs(&self) -> Option<Expr> {
        support::nth_child(&self.syntax, 0)
    }

    pub fn op_token(&self) -> Option<SyntaxToken> {
        support::token(
            &self.syntax,
            &[
                SyntaxKind::SEMICOLON,
                SyntaxKind::COMMA,
                SyntaxKind::EQ,
                SyntaxKind::PLUS_EQ,
                SyntaxKind::LT_GT,
                SyntaxKind::PIPE2,
                SyntaxKind::AMP2,
                SyntaxKind::EQ2,
                SyntaxKind::BANG_EQ,
                SyntaxKind::LT,
                SyntaxKind::LT_EQ,
                SyntaxKind::GT,
                SyntaxKind::GT_EQ,
                SyntaxKind::PLUS,
                SyntaxKind::MINUS,
                SyntaxKind::STAR,
                SyntaxKind::SLASH,
                SyntaxKind::PERCENT,
                SyntaxKind::CARET,
                SyntaxKind::TILDE,
                SyntaxKind::COLON,
            ],
        )
    }

    pub fn rhs(&self) -> Option<Expr> {
        support::nth_child(&self.syntax, 1)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ArgList {
    syntax: SyntaxNode,
}

impl AstNode for ArgList {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::ARG_LIST
    }

    fn cast(syntax: SyntaxNode) -> Option<Self> {
        Self::can_cast(syntax.kind()).then_some(Self { syntax })
    }

    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

impl ArgList {
    pub fn l_paren_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, &[SyntaxKind::L_PAREN])
    }

    pub fn args(&self) -> AstChildren<Expr> {
        support::children(&self.syntax)
    }

    pub fn r_paren_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, &[SyntaxKind::R_PAREN])
    }
}
