//! Generates `src/nodes/generated.rs` from `scarpet.ungram` and fails if the
//! checked-in file is stale. On a mismatch the file is rewritten in place —
//! re-run the test and commit the result.

use std::collections::BTreeMap;
use std::path::PathBuf;

use ungrammar::{Grammar, Rule};

#[test]
fn generated_nodes_are_current() {
    let crate_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let grammar: Grammar = std::fs::read_to_string(crate_root.join("scarpet.ungram"))
        .expect("read scarpet.ungram")
        .parse()
        .expect("parse scarpet.ungram");

    let generated = rustfmt(&generate(&grammar));
    let path = crate_root.join("src/nodes/generated.rs");
    let on_disk = std::fs::read_to_string(&path).unwrap_or_default();
    if normalize(&on_disk) != normalize(&generated) {
        std::fs::write(&path, &generated).expect("write generated.rs");
        panic!(
            "{} was stale and has been regenerated — re-run the test and commit it",
            path.display()
        );
    }
}

fn normalize(s: &str) -> String {
    s.replace("\r\n", "\n").trim_end().to_string()
}

/// Pipe through `rustfmt` so the emitted file always satisfies
/// `cargo fmt --check`. rustfmt ships as a rustup component alongside the
/// toolchain that builds this test, so failing loudly beats drifting quietly.
fn rustfmt(text: &str) -> String {
    use std::io::Write as _;
    use std::process::{Command, Stdio};
    let mut child = Command::new("rustfmt")
        .args(["--edition", "2024"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .expect("spawn rustfmt (rustup component add rustfmt)");
    child
        .stdin
        .take()
        .expect("rustfmt stdin")
        .write_all(text.as_bytes())
        .expect("write to rustfmt");
    let out = child.wait_with_output().expect("run rustfmt");
    assert!(out.status.success(), "rustfmt rejected the generated code");
    String::from_utf8(out.stdout).expect("rustfmt output is UTF-8")
}

// ====================================================================
// Code generation
// ====================================================================

/// A field of a generated node struct.
enum Field {
    /// A child node: `pub fn name(&self) -> Option<Ty>` (or `AstChildren<Ty>`
    /// when `many`, or `nth_child(_, index)` when the type repeats in the
    /// rule, as in `BinExpr`'s `lhs`/`rhs`).
    Node {
        name: String,
        ty: String,
        many: bool,
        index: Option<usize>,
    },
    /// A token: `pub fn name(&self) -> Option<SyntaxToken>` matching any of
    /// `kinds`.
    Token { name: String, kinds: Vec<String> },
}

fn generate(grammar: &Grammar) -> String {
    let mut out = String::new();
    out.push_str("//! Generated by `tests/sourcegen.rs` from `scarpet.ungram` — do not edit.\n\n");
    out.push_str("use super::{AstChildren, AstNode, support};\n");
    out.push_str("use crate::syntax::{SyntaxKind, SyntaxNode, SyntaxToken};\n");

    for node in grammar.iter() {
        let data = &grammar[node];
        if let Rule::Alt(variants) = &data.rule
            && variants.iter().all(|rule| matches!(rule, Rule::Node(_)))
        {
            let variants: Vec<&str> = variants
                .iter()
                .map(|rule| match rule {
                    Rule::Node(n) => grammar[*n].name.as_str(),
                    _ => unreachable!("guard restricts variants to Rule::Node"),
                })
                .collect();
            generate_enum(&mut out, &data.name, &variants);
        } else {
            let mut fields = Vec::new();
            lower_rule(grammar, &data.rule, None, &mut fields);
            dedup_identical_fields(&mut fields);
            dedup_node_fields(&mut fields);
            generate_struct(&mut out, &data.name, &fields);
        }
    }
    out
}

fn generate_struct(out: &mut String, name: &str, fields: &[Field]) {
    let kind = screaming_snake(name);
    out.push_str(&format!(
        r#"
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct {name} {{
    syntax: SyntaxNode,
}}

impl AstNode for {name} {{
    fn can_cast(kind: SyntaxKind) -> bool {{
        kind == SyntaxKind::{kind}
    }}

    fn cast(syntax: SyntaxNode) -> Option<Self> {{
        Self::can_cast(syntax.kind()).then_some(Self {{ syntax }})
    }}

    fn syntax(&self) -> &SyntaxNode {{
        &self.syntax
    }}
}}
"#
    ));
    if fields.is_empty() {
        return;
    }
    out.push_str(&format!("\nimpl {name} {{\n"));
    let mut first = true;
    for field in fields {
        if !first {
            out.push('\n');
        }
        first = false;
        match field {
            Field::Node {
                name,
                ty,
                many,
                index,
            } => {
                if *many {
                    out.push_str(&format!(
                        "    pub fn {name}(&self) -> AstChildren<{ty}> {{ support::children(&self.syntax) }}\n"
                    ));
                } else if let Some(index) = index {
                    out.push_str(&format!(
                        "    pub fn {name}(&self) -> Option<{ty}> {{ support::nth_child(&self.syntax, {index}) }}\n"
                    ));
                } else {
                    out.push_str(&format!(
                        "    pub fn {name}(&self) -> Option<{ty}> {{ support::child(&self.syntax) }}\n"
                    ));
                }
            }
            Field::Token { name, kinds } => {
                let kinds = kinds
                    .iter()
                    .map(|k| format!("SyntaxKind::{k}"))
                    .collect::<Vec<_>>()
                    .join(", ");
                out.push_str(&format!(
                    "    pub fn {name}(&self) -> Option<SyntaxToken> {{ support::token(&self.syntax, &[{kinds}]) }}\n"
                ));
            }
        }
    }
    out.push_str("}\n");
}

fn generate_enum(out: &mut String, name: &str, variants: &[&str]) {
    out.push_str(&format!(
        "\n#[derive(Debug, Clone, PartialEq, Eq, Hash)]\npub enum {name} {{\n"
    ));
    for v in variants {
        out.push_str(&format!("    {v}({v}),\n"));
    }
    out.push_str("}\n");

    out.push_str(&format!("\nimpl AstNode for {name} {{\n"));
    let kinds = variants
        .iter()
        .map(|v| format!("SyntaxKind::{}", screaming_snake(v)))
        .collect::<Vec<_>>()
        .join(" | ");
    out.push_str(&format!(
        "    fn can_cast(kind: SyntaxKind) -> bool {{ matches!(kind, {kinds}) }}\n"
    ));
    out.push_str("\n    fn cast(syntax: SyntaxNode) -> Option<Self> {\n        let node = match syntax.kind() {\n");
    for v in variants {
        out.push_str(&format!(
            "            SyntaxKind::{} => {name}::{v}({v} {{ syntax }}),\n",
            screaming_snake(v)
        ));
    }
    out.push_str("            _ => return None,\n        };\n        Some(node)\n    }\n");
    out.push_str("\n    fn syntax(&self) -> &SyntaxNode {\n        match self {\n");
    for v in variants {
        out.push_str(&format!("            {name}::{v}(it) => &it.syntax,\n"));
    }
    out.push_str("        }\n    }\n}\n");
}

/// Flatten a node's rule into accessor fields. A labeled sequence /
/// repetition (`args:(Expr (',' Expr)*)`) becomes one `many` field over the
/// node type it repeats; separator tokens inside it are not surfaced.
fn lower_rule(grammar: &Grammar, rule: &Rule, label: Option<&str>, acc: &mut Vec<Field>) {
    match rule {
        Rule::Labeled { label, rule } => lower_rule(grammar, rule, Some(label), acc),
        Rule::Opt(inner) => lower_rule(grammar, inner, label, acc),
        Rule::Node(node) => {
            let ty = grammar[*node].name.clone();
            let name = label.map(str::to_string).unwrap_or_else(|| snake_case(&ty));
            acc.push(Field::Node {
                name,
                ty,
                many: false,
                index: None,
            });
        }
        Rule::Token(token) => {
            let (base, kind) = token_info(&grammar[*token].name);
            let name = format!("{}_token", label.unwrap_or(base));
            acc.push(Field::Token {
                name,
                kinds: vec![kind.to_string()],
            });
        }
        Rule::Alt(alts) => {
            if alts.iter().all(|r| matches!(r, Rule::Token(_))) {
                // A token alternation (`value:`, `op:`) becomes one token accessor.
                let kinds = alts
                    .iter()
                    .map(|r| match r {
                        Rule::Token(t) => token_info(&grammar[*t].name).1.to_string(),
                        _ => unreachable!("checked above"),
                    })
                    .collect();
                let name = format!("{}_token", label.expect("a token alternation is labeled"));
                acc.push(Field::Token { name, kinds });
            } else {
                // Structural alternatives, such as the two spellings of `ListExpr`,
                // surface the union of accessors from all branches.
                for r in alts {
                    lower_rule(grammar, r, label, acc);
                }
            }
        }
        Rule::Seq(rules) => {
            if let Some(label) = label {
                // A labeled sequence is a separated list — surface it as one
                // `many` accessor over its node type.
                let mut tys = Vec::new();
                collect_node_types(grammar, rule, &mut tys);
                tys.dedup();
                let [ty] = tys.as_slice() else {
                    panic!("labeled sequence must repeat one node type, got {tys:?}");
                };
                acc.push(Field::Node {
                    name: label.to_string(),
                    ty: ty.clone(),
                    many: true,
                    index: None,
                });
            } else {
                for r in rules {
                    lower_rule(grammar, r, None, acc);
                }
            }
        }
        Rule::Rep(inner) => {
            let mut tys = Vec::new();
            collect_node_types(grammar, inner, &mut tys);
            tys.dedup();
            let [ty] = tys.as_slice() else {
                panic!("repetition must repeat one node type, got {tys:?}");
            };
            let name = label
                .map(str::to_string)
                .unwrap_or_else(|| format!("{}s", snake_case(ty)));
            acc.push(Field::Node {
                name,
                ty: ty.clone(),
                many: true,
                index: None,
            });
        }
    }
}

/// Every node type mentioned anywhere under `rule`, in order.
fn collect_node_types(grammar: &Grammar, rule: &Rule, acc: &mut Vec<String>) {
    match rule {
        Rule::Node(n) => acc.push(grammar[*n].name.clone()),
        Rule::Token(_) => {}
        Rule::Labeled { rule, .. } | Rule::Opt(rule) | Rule::Rep(rule) => {
            collect_node_types(grammar, rule, acc)
        }
        Rule::Seq(rules) | Rule::Alt(rules) => {
            for r in rules {
                collect_node_types(grammar, r, acc);
            }
        }
    }
}

/// Collapse fields that several `Alt` branches contribute identically (the
/// two `ListExpr` spellings both label their elements `args`). A field name
/// reused with a different shape is a grammar bug.
fn dedup_identical_fields(fields: &mut Vec<Field>) {
    let mut seen: BTreeMap<String, String> = BTreeMap::new();
    fields.retain(|field| {
        let (name, shape) = match field {
            Field::Node { name, ty, many, .. } => (name.clone(), format!("node {ty} many={many}")),
            Field::Token { name, kinds } => (name.clone(), format!("token {}", kinds.join(" "))),
        };
        match seen.get(&name) {
            Some(prev) if *prev == shape => false,
            Some(prev) => panic!("field `{name}` has conflicting shapes: {prev} vs {shape}"),
            None => {
                seen.insert(name, shape);
                true
            }
        }
    });
}

/// When one node type fills several single-child fields (`lhs`/`rhs`), switch
/// them to positional `nth_child` lookups.
fn dedup_node_fields(fields: &mut [Field]) {
    let mut counts: BTreeMap<String, usize> = BTreeMap::new();
    for field in fields.iter() {
        if let Field::Node {
            ty, many: false, ..
        } = field
        {
            *counts.entry(ty.clone()).or_default() += 1;
        }
    }
    let mut seen: BTreeMap<String, usize> = BTreeMap::new();
    for field in fields.iter_mut() {
        if let Field::Node {
            ty,
            many: false,
            index,
            ..
        } = field
            && counts[ty.as_str()] > 1
        {
            let next = seen.entry(ty.clone()).or_default();
            *index = Some(*next);
            *next += 1;
        }
    }
}

fn token_info(token: &str) -> (&'static str, &'static str) {
    match token {
        "(" => ("l_paren", "L_PAREN"),
        ")" => ("r_paren", "R_PAREN"),
        "[" => ("l_brack", "L_BRACK"),
        "]" => ("r_brack", "R_BRACK"),
        "{" => ("l_brace", "L_BRACE"),
        "}" => ("r_brace", "R_BRACE"),
        "," => ("comma", "COMMA"),
        ";" => ("semicolon", "SEMICOLON"),
        "->" => ("arrow", "ARROW"),
        "=" => ("eq", "EQ"),
        "+=" => ("plus_eq", "PLUS_EQ"),
        "<>" => ("lt_gt", "LT_GT"),
        "||" => ("pipe2", "PIPE2"),
        "&&" => ("amp2", "AMP2"),
        "==" => ("eq2", "EQ2"),
        "!=" => ("bang_eq", "BANG_EQ"),
        "<" => ("lt", "LT"),
        "<=" => ("lt_eq", "LT_EQ"),
        ">" => ("gt", "GT"),
        ">=" => ("gt_eq", "GT_EQ"),
        "+" => ("plus", "PLUS"),
        "-" => ("minus", "MINUS"),
        "*" => ("star", "STAR"),
        "/" => ("slash", "SLASH"),
        "%" => ("percent", "PERCENT"),
        "^" => ("caret", "CARET"),
        "~" => ("tilde", "TILDE"),
        ":" => ("colon", "COLON"),
        "..." => ("dot3", "DOT3"),
        "!" => ("bang", "BANG"),
        "number" => ("number", "NUMBER"),
        "string" => ("string", "STRING"),
        "ident" => ("ident", "IDENT"),
        // Contextual keywords: lexed as `IDENT`, then reclassified by the
        // parser only when they introduce their corresponding literal form.
        "l" => ("l", "L_KW"),
        "m" => ("m", "M_KW"),
        other => panic!("unknown token in scarpet.ungram: {other:?}"),
    }
}

fn screaming_snake(name: &str) -> String {
    let mut out = String::new();
    for (i, ch) in name.chars().enumerate() {
        if ch.is_ascii_uppercase() && i > 0 {
            out.push('_');
        }
        out.push(ch.to_ascii_uppercase());
    }
    out
}

fn snake_case(name: &str) -> String {
    screaming_snake(name).to_ascii_lowercase()
}
