//! Generates `scarpet-syntax/src/syntax_kind.rs` and
//! `scarpet-syntax/src/cst/generated.rs` from `scarpet-syntax/scarpet.ungram`
//! (parsed with the `ungrammar` crate) plus the static token tables below.
//!
//! The generated files are checked in; the `generated_code_is_up_to_date`
//! test keeps them in sync with the grammar.

use std::{
    fmt::Write as _,
    fs,
    io::Write as _,
    path::{Path, PathBuf},
    process::{Command, Stdio},
};

use ungrammar::{Grammar, Rule};

pub type Result<T> = std::result::Result<T, Box<dyn std::error::Error>>;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Mode {
    /// Write the generated files to disk (`cargo xtask codegen`).
    Overwrite,
    /// Only check that the files on disk are current (used by the test).
    Verify,
}

const GENERATED_HEADER: &str = "//! generated by `cargo xtask codegen`, do not edit by hand.";

/// All token kinds, in the frozen `SyntaxKind` discriminant order.
///
/// `WHITESPACE`, `NEWLINE`, `COMMENT` (trivia) and `ERROR_TOKEN` never appear
/// in the grammar, but the lexer produces them.
const TOKEN_KINDS: &[&str] = &[
    "WHITESPACE",
    "NEWLINE",
    "COMMENT",
    "NUMBER",
    "STRING",
    "IDENT",
    "OPEN_PAREN",
    "CLOSE_PAREN",
    "OPEN_BRACK",
    "CLOSE_BRACK",
    "OPEN_BRACE",
    "CLOSE_BRACE",
    "EQ_EQ",
    "BANG_EQ",
    "LT",
    "LT_EQ",
    "GT",
    "GT_EQ",
    "AND_AND",
    "OR_OR",
    "BANG",
    "PLUS",
    "MINUS",
    "STAR",
    "SLASH",
    "PERCENT",
    "CARET",
    "EQ",
    "PLUS_EQ",
    "SWAP",
    "TILDE",
    "COLON",
    "DOT",
    "ELLIPSIS",
    "COMMA",
    "SEMICOLON",
    "ARROW",
    "ERROR_TOKEN",
];

/// Grammar token text -> `SyntaxKind` variant name.
const TOKEN_TEXTS: &[(&str, &str)] = &[
    ("number", "NUMBER"),
    ("string", "STRING"),
    ("ident", "IDENT"),
    ("(", "OPEN_PAREN"),
    (")", "CLOSE_PAREN"),
    ("[", "OPEN_BRACK"),
    ("]", "CLOSE_BRACK"),
    ("{", "OPEN_BRACE"),
    ("}", "CLOSE_BRACE"),
    ("==", "EQ_EQ"),
    ("!=", "BANG_EQ"),
    ("<", "LT"),
    ("<=", "LT_EQ"),
    (">", "GT"),
    (">=", "GT_EQ"),
    ("&&", "AND_AND"),
    ("||", "OR_OR"),
    ("!", "BANG"),
    ("+", "PLUS"),
    ("-", "MINUS"),
    ("*", "STAR"),
    ("/", "SLASH"),
    ("%", "PERCENT"),
    ("^", "CARET"),
    ("=", "EQ"),
    ("+=", "PLUS_EQ"),
    ("<>", "SWAP"),
    ("~", "TILDE"),
    (":", "COLON"),
    (".", "DOT"),
    ("...", "ELLIPSIS"),
    (",", "COMMA"),
    (";", "SEMICOLON"),
    ("->", "ARROW"),
];

/// All node kinds, in the frozen `SyntaxKind` discriminant order.
///
/// `ERROR` does not appear in the grammar; the parser produces it for
/// unparsable input.
const NODE_KINDS: &[&str] = &[
    "SOURCE_FILE",
    "LITERAL",
    "NAME_REF",
    "CALL_EXPR",
    "ARG_LIST",
    "LIST_EXPR",
    "MAP_EXPR",
    "PAREN_EXPR",
    "PREFIX_EXPR",
    "BIN_EXPR",
    "COMMA_CHAIN",
    "SEMI_CHAIN",
    "EMPTY_ARG",
    "ERROR",
];

pub fn run(mode: Mode) -> Result<()> {
    let root = project_root();
    let grammar_path = root.join("scarpet-syntax/scarpet.ungram");
    let grammar: Grammar = fs::read_to_string(&grammar_path)
        .map_err(|err| format!("failed to read {}: {err}", grammar_path.display()))?
        .parse()
        .map_err(|err| format!("failed to parse {}: {err}", grammar_path.display()))?;

    let ast = lower(&grammar)?;

    let syntax_kinds = reformat(&render_syntax_kinds())?;
    let generated_cst = reformat(&render_cst(&ast))?;

    ensure_file_contents(
        mode,
        &root.join("scarpet-syntax/src/syntax_kind.rs"),
        &syntax_kinds,
    )?;
    ensure_file_contents(
        mode,
        &root.join("scarpet-syntax/src/cst/generated.rs"),
        &generated_cst,
    )?;
    Ok(())
}

fn project_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask manifest dir has a parent")
        .to_path_buf()
}

fn ensure_file_contents(mode: Mode, path: &Path, contents: &str) -> Result<()> {
    match mode {
        Mode::Overwrite => {
            if fs::read_to_string(path).is_ok_and(|on_disk| on_disk == contents) {
                return Ok(());
            }
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent)?;
            }
            fs::write(path, contents)
                .map_err(|err| format!("failed to write {}: {err}", path.display()))?;
            eprintln!("updated {}", path.display());
            Ok(())
        }
        Mode::Verify => {
            let on_disk = fs::read_to_string(path).ok();
            if on_disk.as_deref() == Some(contents) {
                Ok(())
            } else {
                let problem = if on_disk.is_some() {
                    "is out of date"
                } else {
                    "is missing or unreadable"
                };
                Err(format!(
                    "{} {problem}.\nPlease run `cargo xtask codegen` to regenerate it.",
                    path.display()
                )
                .into())
            }
        }
    }
}

/// Runs the text through `rustfmt` so the checked-in files match
/// `cargo fmt --all -- --check`.
fn reformat(text: &str) -> Result<String> {
    let mut child = Command::new("rustfmt")
        .args(["--edition", "2024"])
        .current_dir(project_root())
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .map_err(|err| format!("failed to spawn rustfmt (needed by codegen): {err}"))?;
    child
        .stdin
        .take()
        .expect("stdin was piped")
        .write_all(text.as_bytes())?;
    let output = child.wait_with_output()?;
    if !output.status.success() {
        return Err(format!("rustfmt failed on generated code:\n{text}").into());
    }
    Ok(String::from_utf8(output.stdout)?)
}

fn token_kind_for_text(text: &str) -> Option<&'static str> {
    TOKEN_TEXTS
        .iter()
        .find(|(t, _)| *t == text)
        .map(|(_, kind)| *kind)
}

// ---------------------------------------------------------------------------
// Grammar lowering
// ---------------------------------------------------------------------------

/// A typed-node model lowered from the ungrammar file.
#[derive(Default)]
struct AstSrc {
    nodes: Vec<AstNodeSrc>,
    enums: Vec<AstEnumSrc>,
}

/// A node kind that becomes a struct (e.g. `CallExpr`).
struct AstNodeSrc {
    name: String,
    fields: Vec<Field>,
}

/// A node alternation that becomes an enum (e.g. `Expr`).
struct AstEnumSrc {
    name: String,
    variants: Vec<String>,
}

enum Field {
    /// `support::token(.., SyntaxKind::{kind})`, named `{method}_token`.
    Token { method: String, kind: String },
    Node {
        name: String,
        ty: String,
        cardinality: Cardinality,
    },
}

enum Cardinality {
    /// `support::child` — the only child node of this type.
    Optional,
    /// `support::children` — any number of child nodes of this type.
    Many,
    /// `support::children(..).nth(n)` — the n-th child node of this type
    /// (used when one node has several fields of the same type, e.g.
    /// `BinExpr.lhs` / `BinExpr.rhs`).
    Nth(usize),
}

impl Field {
    fn method_name(&self) -> String {
        match self {
            Field::Token { method, .. } => format!("{method}_token"),
            Field::Node { name, .. } => name.clone(),
        }
    }
}

fn lower(grammar: &Grammar) -> Result<AstSrc> {
    check_token_table(grammar)?;

    let mut res = AstSrc::default();
    for node in grammar.iter() {
        let data = &grammar[node];
        match lower_enum(grammar, &data.rule) {
            Some(variants) => res.enums.push(AstEnumSrc {
                name: data.name.clone(),
                variants,
            }),
            None => {
                let mut fields = Vec::new();
                lower_rule(&mut fields, grammar, None, &data.rule)
                    .map_err(|err| format!("in grammar node {}: {err}", data.name))?;
                disambiguate(&mut fields);
                check_no_duplicate_methods(&data.name, &fields)?;
                res.nodes.push(AstNodeSrc {
                    name: data.name.clone(),
                    fields,
                });
            }
        }
    }

    check_node_table(&res)?;
    // Emit structs in the frozen `NODE_KINDS` order, not grammar order.
    res.nodes.sort_by_key(|node| {
        let kind = to_upper_snake_case(&node.name);
        NODE_KINDS.iter().position(|&k| k == kind)
    });
    Ok(res)
}

/// Every token mentioned in the grammar must be in the static table.
fn check_token_table(grammar: &Grammar) -> Result<()> {
    for token in grammar.tokens() {
        let text = &grammar[token].name;
        if token_kind_for_text(text).is_none() {
            return Err(format!(
                "grammar token '{text}' is missing from the TOKEN_TEXTS table in xtask"
            )
            .into());
        }
    }
    Ok(())
}

/// The grammar's struct nodes must match `NODE_KINDS` (minus `ERROR`).
fn check_node_table(ast: &AstSrc) -> Result<()> {
    let mut expected: Vec<&str> = NODE_KINDS
        .iter()
        .copied()
        .filter(|&k| k != "ERROR")
        .collect();
    let mut actual: Vec<String> = ast
        .nodes
        .iter()
        .map(|node| to_upper_snake_case(&node.name))
        .collect();
    expected.sort_unstable();
    actual.sort_unstable();
    if actual != expected {
        return Err(format!(
            "grammar nodes {actual:?} do not match the NODE_KINDS table {expected:?} \
             — update scarpet.ungram and xtask together"
        )
        .into());
    }
    Ok(())
}

fn check_no_duplicate_methods(node: &str, fields: &[Field]) -> Result<()> {
    let mut names: Vec<String> = fields.iter().map(Field::method_name).collect();
    names.sort_unstable();
    for pair in names.windows(2) {
        if pair[0] == pair[1] {
            return Err(format!(
                "grammar node {node} would generate two `{}` accessors",
                pair[0]
            )
            .into());
        }
    }
    Ok(())
}

/// `A = B | C | D` where all alternatives are nodes becomes an enum.
fn lower_enum(grammar: &Grammar, rule: &Rule) -> Option<Vec<String>> {
    let Rule::Alt(alternatives) = rule else {
        return None;
    };
    alternatives
        .iter()
        .map(|alt| match alt {
            Rule::Node(node) => Some(grammar[*node].name.clone()),
            _ => None,
        })
        .collect()
}

fn lower_rule(
    acc: &mut Vec<Field>,
    grammar: &Grammar,
    label: Option<&str>,
    rule: &Rule,
) -> Result<()> {
    if lower_separated_list(acc, grammar, rule) {
        return Ok(());
    }
    match rule {
        Rule::Node(node) => {
            let ty = grammar[*node].name.clone();
            let name = label.map_or_else(|| to_snake_case(&ty), str::to_owned);
            acc.push(Field::Node {
                name,
                ty,
                cardinality: Cardinality::Optional,
            });
        }
        Rule::Token(token) => {
            let text = &grammar[*token].name;
            let kind = token_kind_for_text(text).expect("checked by check_token_table");
            acc.push(Field::Token {
                method: label.map_or_else(|| kind.to_lowercase(), str::to_owned),
                kind: kind.to_owned(),
            });
        }
        Rule::Rep(inner) => {
            let Rule::Node(node) = &**inner else {
                return Err(format!("unsupported repetition: {rule:?}").into());
            };
            let ty = grammar[*node].name.clone();
            let name = label.map_or_else(|| pluralize(&to_snake_case(&ty)), str::to_owned);
            acc.push(Field::Node {
                name,
                ty,
                cardinality: Cardinality::Many,
            });
        }
        Rule::Opt(inner) => lower_rule(acc, grammar, label, inner)?,
        Rule::Seq(rules) => {
            for rule in rules {
                lower_rule(acc, grammar, None, rule)?;
            }
        }
        Rule::Alt(alternatives) => {
            if !alternatives.iter().all(|alt| matches!(alt, Rule::Token(_))) {
                return Err(format!("unsupported alternation: {rule:?}").into());
            }
            // A labeled token alternation (`op:(..)`) is an operator set: too
            // many tokens for one accessor each, so no accessor is generated;
            // a hand-written ext layer provides `op` lookup instead.
            if label.is_none() {
                for alt in alternatives {
                    lower_rule(acc, grammar, None, alt)?;
                }
            }
        }
        Rule::Labeled { label: l, rule } => lower_rule(acc, grammar, Some(l), rule)?,
    }
    Ok(())
}

/// Detects `T (sep T)* sep?` (e.g. `CommaChain`, `SemiChain`) and lowers it to
/// a single `Many` field, so the head `T` does not also get its own accessor.
fn lower_separated_list(acc: &mut Vec<Field>, grammar: &Grammar, rule: &Rule) -> bool {
    let Rule::Seq(rules) = rule else {
        return false;
    };
    let (head, rep, trailing) = match rules.as_slice() {
        [Rule::Node(head), Rule::Rep(rep)] => (head, rep, None),
        [Rule::Node(head), Rule::Rep(rep), Rule::Opt(trailing)] => (head, rep, Some(trailing)),
        _ => return false,
    };
    let Rule::Seq(rep_rules) = &**rep else {
        return false;
    };
    let [Rule::Token(sep), Rule::Node(tail)] = rep_rules.as_slice() else {
        return false;
    };
    if tail != head {
        return false;
    }
    if let Some(trailing) = trailing
        && !matches!(&**trailing, Rule::Token(t) if t == sep)
    {
        return false;
    }
    let ty = grammar[*head].name.clone();
    acc.push(Field::Node {
        name: pluralize(&to_snake_case(&ty)),
        ty,
        cardinality: Cardinality::Many,
    });
    true
}

/// When a node has several fields of the same node type (`BinExpr.lhs` /
/// `BinExpr.rhs`), `support::child` cannot tell them apart; switch those
/// fields to positional (`nth`) access.
fn disambiguate(fields: &mut [Field]) {
    let mut counts: Vec<(String, usize)> = Vec::new();
    for field in fields.iter() {
        if let Field::Node { ty, .. } = field {
            match counts.iter_mut().find(|(t, _)| t == ty) {
                Some((_, count)) => *count += 1,
                None => counts.push((ty.clone(), 1)),
            }
        }
    }
    for (ty, count) in counts {
        if count < 2 {
            continue;
        }
        let mut index = 0;
        for field in fields.iter_mut() {
            if let Field::Node {
                ty: field_ty,
                cardinality,
                ..
            } = field
                && *field_ty == ty
            {
                *cardinality = Cardinality::Nth(index);
                index += 1;
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

fn render_syntax_kinds() -> String {
    let mut buf = String::new();
    buf.push_str(GENERATED_HEADER);
    buf.push_str("\n\n");
    buf.push_str(
        "/// The kind of a token or node in the Scarpet syntax tree.\n\
         ///\n\
         /// Token kinds come first, node kinds after; `__LAST` is a sentinel, not a\n\
         /// real kind. The discriminant is the raw `u16` stored in the rowan tree.\n",
    );
    buf.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]\n");
    buf.push_str("#[repr(u16)]\n");
    buf.push_str(
        "#[allow(non_camel_case_types, clippy::manual_non_exhaustive, clippy::upper_case_acronyms)]\n",
    );
    buf.push_str("pub enum SyntaxKind {\n");
    buf.push_str("    // ----- tokens -----\n");
    for kind in TOKEN_KINDS {
        writeln!(buf, "    {kind},").unwrap();
    }
    buf.push_str("    // ----- nodes -----\n");
    for kind in NODE_KINDS {
        writeln!(buf, "    {kind},").unwrap();
    }
    buf.push_str("    /// Sentinel, not a real kind; keep last.\n");
    buf.push_str("    #[doc(hidden)]\n");
    buf.push_str("    __LAST,\n");
    buf.push_str("}\n\n");

    buf.push_str("impl SyntaxKind {\n");
    buf.push_str(
        "    /// Trivia tokens: whitespace, newlines (including the `$` newline\n\
         \x20   /// stand-in) and comments.\n",
    );
    buf.push_str("    pub const fn is_trivia(self) -> bool {\n");
    buf.push_str(
        "        matches!(self, SyntaxKind::WHITESPACE | SyntaxKind::NEWLINE | SyntaxKind::COMMENT)\n",
    );
    buf.push_str("    }\n\n");

    buf.push_str(
        "    /// Converts a raw `u16` (e.g. from `rowan::SyntaxKind`) back into a kind.\n\
         \x20   ///\n\
         \x20   /// # Panics\n\
         \x20   ///\n\
         \x20   /// Panics if `raw` does not correspond to a kind.\n",
    );
    buf.push_str("    pub fn from_raw(raw: u16) -> SyntaxKind {\n");
    buf.push_str("        match raw {\n");
    for (raw, kind) in TOKEN_KINDS.iter().chain(NODE_KINDS).enumerate() {
        writeln!(buf, "            {raw} => SyntaxKind::{kind},").unwrap();
    }
    buf.push_str("            _ => panic!(\"invalid SyntaxKind raw value: {raw}\"),\n");
    buf.push_str("        }\n");
    buf.push_str("    }\n\n");

    buf.push_str("    /// Converts the kind into its raw `u16` representation.\n");
    buf.push_str("    pub const fn to_raw(self) -> u16 {\n");
    buf.push_str("        self as u16\n");
    buf.push_str("    }\n");
    buf.push_str("}\n\n");

    buf.push_str("/// Same as [`SyntaxKind::from_raw`]: panics if `raw` is not a valid kind.\n");
    buf.push_str("impl From<u16> for SyntaxKind {\n");
    buf.push_str("    fn from(raw: u16) -> SyntaxKind {\n");
    buf.push_str("        SyntaxKind::from_raw(raw)\n");
    buf.push_str("    }\n");
    buf.push_str("}\n\n");

    buf.push_str("impl From<SyntaxKind> for u16 {\n");
    buf.push_str("    fn from(kind: SyntaxKind) -> u16 {\n");
    buf.push_str("        kind.to_raw()\n");
    buf.push_str("    }\n");
    buf.push_str("}\n");
    buf
}

fn render_cst(ast: &AstSrc) -> String {
    let mut buf = String::new();
    buf.push_str(GENERATED_HEADER);
    buf.push_str("\n\n");
    buf.push_str("use rowan::ast::{AstChildren, AstNode, support};\n\n");
    buf.push_str(
        "use crate::{\n    syntax::{ScarpetLanguage, SyntaxNode, SyntaxToken},\n    syntax_kind::SyntaxKind,\n};\n",
    );

    for node in &ast.nodes {
        render_node(&mut buf, node);
    }
    for enum_src in &ast.enums {
        render_enum(&mut buf, enum_src);
    }
    buf
}

fn render_node(buf: &mut String, node: &AstNodeSrc) {
    let name = &node.name;
    let kind = to_upper_snake_case(name);

    write!(
        buf,
        "\n#[derive(Debug, Clone, PartialEq, Eq, Hash)]\n\
         pub struct {name} {{\n    pub(crate) syntax: SyntaxNode,\n}}\n"
    )
    .unwrap();

    if !node.fields.is_empty() {
        write!(buf, "\nimpl {name} {{\n").unwrap();
        for field in &node.fields {
            render_field(buf, field);
        }
        buf.push_str("}\n");
    }

    write!(
        buf,
        "\nimpl AstNode for {name} {{\n\
         \x20   type Language = ScarpetLanguage;\n\
         \x20   fn can_cast(kind: SyntaxKind) -> bool {{\n\
         \x20       kind == SyntaxKind::{kind}\n\
         \x20   }}\n\
         \x20   fn cast(syntax: SyntaxNode) -> Option<{name}> {{\n\
         \x20       if {name}::can_cast(syntax.kind()) {{ Some({name} {{ syntax }}) }} else {{ None }}\n\
         \x20   }}\n\
         \x20   fn syntax(&self) -> &SyntaxNode {{\n\
         \x20       &self.syntax\n\
         \x20   }}\n\
         }}\n"
    )
    .unwrap();
}

fn render_field(buf: &mut String, field: &Field) {
    let method = field.method_name();
    match field {
        Field::Token { kind, .. } => {
            write!(
                buf,
                "    pub fn {method}(&self) -> Option<SyntaxToken> {{\n\
                 \x20       support::token(&self.syntax, SyntaxKind::{kind})\n\
                 \x20   }}\n"
            )
            .unwrap();
        }
        Field::Node {
            ty, cardinality, ..
        } => match cardinality {
            Cardinality::Optional => {
                write!(
                    buf,
                    "    pub fn {method}(&self) -> Option<{ty}> {{\n\
                     \x20       support::child(&self.syntax)\n\
                     \x20   }}\n"
                )
                .unwrap();
            }
            Cardinality::Many => {
                write!(
                    buf,
                    "    pub fn {method}(&self) -> AstChildren<{ty}> {{\n\
                     \x20       support::children(&self.syntax)\n\
                     \x20   }}\n"
                )
                .unwrap();
            }
            Cardinality::Nth(n) => {
                let access = if *n == 0 {
                    ".next()".to_owned()
                } else {
                    format!(".nth({n})")
                };
                write!(
                    buf,
                    "    pub fn {method}(&self) -> Option<{ty}> {{\n\
                     \x20       support::children(&self.syntax){access}\n\
                     \x20   }}\n"
                )
                .unwrap();
            }
        },
    }
}

fn render_enum(buf: &mut String, enum_src: &AstEnumSrc) {
    let name = &enum_src.name;

    write!(
        buf,
        "\n#[derive(Debug, Clone, PartialEq, Eq, Hash)]\npub enum {name} {{\n"
    )
    .unwrap();
    for variant in &enum_src.variants {
        writeln!(buf, "    {variant}({variant}),").unwrap();
    }
    buf.push_str("}\n");

    write!(buf, "\nimpl AstNode for {name} {{\n").unwrap();
    buf.push_str("    type Language = ScarpetLanguage;\n");
    buf.push_str("    fn can_cast(kind: SyntaxKind) -> bool {\n");
    buf.push_str("        matches!(\n            kind,\n            ");
    let kinds: Vec<String> = enum_src
        .variants
        .iter()
        .map(|variant| format!("SyntaxKind::{}", to_upper_snake_case(variant)))
        .collect();
    buf.push_str(&kinds.join(" | "));
    buf.push_str("\n        )\n    }\n");
    writeln!(buf, "    fn cast(syntax: SyntaxNode) -> Option<{name}> {{").unwrap();
    buf.push_str("        let res = match syntax.kind() {\n");
    for variant in &enum_src.variants {
        writeln!(
            buf,
            "            SyntaxKind::{} => {name}::{variant}({variant} {{ syntax }}),",
            to_upper_snake_case(variant)
        )
        .unwrap();
    }
    buf.push_str("            _ => return None,\n");
    buf.push_str("        };\n        Some(res)\n    }\n");
    buf.push_str("    fn syntax(&self) -> &SyntaxNode {\n        match self {\n");
    for variant in &enum_src.variants {
        writeln!(buf, "            {name}::{variant}(it) => &it.syntax,").unwrap();
    }
    buf.push_str("        }\n    }\n}\n");

    for variant in &enum_src.variants {
        write!(
            buf,
            "\nimpl From<{variant}> for {name} {{\n\
             \x20   fn from(node: {variant}) -> {name} {{\n\
             \x20       {name}::{variant}(node)\n\
             \x20   }}\n\
             }}\n"
        )
        .unwrap();
    }
}

// ---------------------------------------------------------------------------
// Naming helpers
// ---------------------------------------------------------------------------

fn to_upper_snake_case(s: &str) -> String {
    let mut buf = String::with_capacity(s.len() + 2);
    for (i, ch) in s.chars().enumerate() {
        if ch.is_ascii_uppercase() && i != 0 {
            buf.push('_');
        }
        buf.push(ch.to_ascii_uppercase());
    }
    buf
}

fn to_snake_case(s: &str) -> String {
    to_upper_snake_case(s).to_lowercase()
}

fn pluralize(s: &str) -> String {
    format!("{s}s")
}

#[cfg(test)]
mod tests {
    use super::{Mode, run};

    /// The checked-in generated files must match what codegen produces from
    /// the current grammar. If this fails, run `cargo xtask codegen`.
    #[test]
    fn generated_code_is_up_to_date() {
        run(Mode::Verify).unwrap_or_else(|err| panic!("{err}"));
    }
}
