//! generated by `cargo xtask codegen`, do not edit by hand.

/// The kind of a token or node in the Scarpet syntax tree.
///
/// Token kinds come first, node kinds after; `__LAST` is a sentinel, not a
/// real kind. The discriminant is the raw `u16` stored in the rowan tree.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(u16)]
#[allow(
    non_camel_case_types,
    clippy::manual_non_exhaustive,
    clippy::upper_case_acronyms
)]
pub enum SyntaxKind {
    // ----- tokens -----
    WHITESPACE,
    NEWLINE,
    COMMENT,
    NUMBER,
    STRING,
    IDENT,
    OPEN_PAREN,
    CLOSE_PAREN,
    OPEN_BRACK,
    CLOSE_BRACK,
    OPEN_BRACE,
    CLOSE_BRACE,
    EQ_EQ,
    BANG_EQ,
    LT,
    LT_EQ,
    GT,
    GT_EQ,
    AND_AND,
    OR_OR,
    BANG,
    PLUS,
    MINUS,
    STAR,
    SLASH,
    PERCENT,
    CARET,
    EQ,
    PLUS_EQ,
    SWAP,
    TILDE,
    COLON,
    DOT,
    ELLIPSIS,
    COMMA,
    SEMICOLON,
    ARROW,
    ERROR_TOKEN,
    // ----- nodes -----
    SOURCE_FILE,
    LITERAL,
    NAME_REF,
    CALL_EXPR,
    ARG_LIST,
    LIST_EXPR,
    MAP_EXPR,
    PAREN_EXPR,
    PREFIX_EXPR,
    BIN_EXPR,
    COMMA_CHAIN,
    SEMI_CHAIN,
    EMPTY_ARG,
    ERROR,
    /// Sentinel, not a real kind; keep last.
    #[doc(hidden)]
    __LAST,
}

impl SyntaxKind {
    /// Trivia tokens: whitespace, newlines (including the `$` newline
    /// stand-in) and comments.
    pub const fn is_trivia(self) -> bool {
        matches!(
            self,
            SyntaxKind::WHITESPACE | SyntaxKind::NEWLINE | SyntaxKind::COMMENT
        )
    }

    /// Converts a raw `u16` (e.g. from `rowan::SyntaxKind`) back into a kind.
    ///
    /// # Panics
    ///
    /// Panics if `raw` does not correspond to a kind.
    pub fn from_raw(raw: u16) -> SyntaxKind {
        match raw {
            0 => SyntaxKind::WHITESPACE,
            1 => SyntaxKind::NEWLINE,
            2 => SyntaxKind::COMMENT,
            3 => SyntaxKind::NUMBER,
            4 => SyntaxKind::STRING,
            5 => SyntaxKind::IDENT,
            6 => SyntaxKind::OPEN_PAREN,
            7 => SyntaxKind::CLOSE_PAREN,
            8 => SyntaxKind::OPEN_BRACK,
            9 => SyntaxKind::CLOSE_BRACK,
            10 => SyntaxKind::OPEN_BRACE,
            11 => SyntaxKind::CLOSE_BRACE,
            12 => SyntaxKind::EQ_EQ,
            13 => SyntaxKind::BANG_EQ,
            14 => SyntaxKind::LT,
            15 => SyntaxKind::LT_EQ,
            16 => SyntaxKind::GT,
            17 => SyntaxKind::GT_EQ,
            18 => SyntaxKind::AND_AND,
            19 => SyntaxKind::OR_OR,
            20 => SyntaxKind::BANG,
            21 => SyntaxKind::PLUS,
            22 => SyntaxKind::MINUS,
            23 => SyntaxKind::STAR,
            24 => SyntaxKind::SLASH,
            25 => SyntaxKind::PERCENT,
            26 => SyntaxKind::CARET,
            27 => SyntaxKind::EQ,
            28 => SyntaxKind::PLUS_EQ,
            29 => SyntaxKind::SWAP,
            30 => SyntaxKind::TILDE,
            31 => SyntaxKind::COLON,
            32 => SyntaxKind::DOT,
            33 => SyntaxKind::ELLIPSIS,
            34 => SyntaxKind::COMMA,
            35 => SyntaxKind::SEMICOLON,
            36 => SyntaxKind::ARROW,
            37 => SyntaxKind::ERROR_TOKEN,
            38 => SyntaxKind::SOURCE_FILE,
            39 => SyntaxKind::LITERAL,
            40 => SyntaxKind::NAME_REF,
            41 => SyntaxKind::CALL_EXPR,
            42 => SyntaxKind::ARG_LIST,
            43 => SyntaxKind::LIST_EXPR,
            44 => SyntaxKind::MAP_EXPR,
            45 => SyntaxKind::PAREN_EXPR,
            46 => SyntaxKind::PREFIX_EXPR,
            47 => SyntaxKind::BIN_EXPR,
            48 => SyntaxKind::COMMA_CHAIN,
            49 => SyntaxKind::SEMI_CHAIN,
            50 => SyntaxKind::EMPTY_ARG,
            51 => SyntaxKind::ERROR,
            _ => panic!("invalid SyntaxKind raw value: {raw}"),
        }
    }

    /// Converts the kind into its raw `u16` representation.
    pub const fn to_raw(self) -> u16 {
        self as u16
    }
}

/// Same as [`SyntaxKind::from_raw`]: panics if `raw` is not a valid kind.
impl From<u16> for SyntaxKind {
    fn from(raw: u16) -> SyntaxKind {
        SyntaxKind::from_raw(raw)
    }
}

impl From<SyntaxKind> for u16 {
    fn from(kind: SyntaxKind) -> u16 {
        kind.to_raw()
    }
}
