//! generated by `cargo xtask codegen`, do not edit by hand.

use rowan::ast::{AstChildren, AstNode, support};

use crate::{
    syntax::{ScarpetLanguage, SyntaxNode, SyntaxToken},
    syntax_kind::SyntaxKind,
};

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct SourceFile {
    pub(crate) syntax: SyntaxNode,
}

impl SourceFile {
    pub fn expr(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
}

impl AstNode for SourceFile {
    type Language = ScarpetLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::SOURCE_FILE
    }
    fn cast(syntax: SyntaxNode) -> Option<SourceFile> {
        if SourceFile::can_cast(syntax.kind()) {
            Some(SourceFile { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Literal {
    pub(crate) syntax: SyntaxNode,
}

impl Literal {
    pub fn number_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::NUMBER)
    }
    pub fn string_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::STRING)
    }
}

impl AstNode for Literal {
    type Language = ScarpetLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::LITERAL
    }
    fn cast(syntax: SyntaxNode) -> Option<Literal> {
        if Literal::can_cast(syntax.kind()) {
            Some(Literal { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct NameRef {
    pub(crate) syntax: SyntaxNode,
}

impl NameRef {
    pub fn ident_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::IDENT)
    }
}

impl AstNode for NameRef {
    type Language = ScarpetLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::NAME_REF
    }
    fn cast(syntax: SyntaxNode) -> Option<NameRef> {
        if NameRef::can_cast(syntax.kind()) {
            Some(NameRef { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct CallExpr {
    pub(crate) syntax: SyntaxNode,
}

impl CallExpr {
    pub fn name_ref(&self) -> Option<NameRef> {
        support::child(&self.syntax)
    }
    pub fn arg_list(&self) -> Option<ArgList> {
        support::child(&self.syntax)
    }
}

impl AstNode for CallExpr {
    type Language = ScarpetLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::CALL_EXPR
    }
    fn cast(syntax: SyntaxNode) -> Option<CallExpr> {
        if CallExpr::can_cast(syntax.kind()) {
            Some(CallExpr { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ArgList {
    pub(crate) syntax: SyntaxNode,
}

impl ArgList {
    pub fn open_paren_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::OPEN_PAREN)
    }
    pub fn exprs(&self) -> AstChildren<Expr> {
        support::children(&self.syntax)
    }
    pub fn close_paren_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::CLOSE_PAREN)
    }
}

impl AstNode for ArgList {
    type Language = ScarpetLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::ARG_LIST
    }
    fn cast(syntax: SyntaxNode) -> Option<ArgList> {
        if ArgList::can_cast(syntax.kind()) {
            Some(ArgList { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ListExpr {
    pub(crate) syntax: SyntaxNode,
}

impl ListExpr {
    pub fn open_brack_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::OPEN_BRACK)
    }
    pub fn exprs(&self) -> AstChildren<Expr> {
        support::children(&self.syntax)
    }
    pub fn close_brack_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::CLOSE_BRACK)
    }
}

impl AstNode for ListExpr {
    type Language = ScarpetLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::LIST_EXPR
    }
    fn cast(syntax: SyntaxNode) -> Option<ListExpr> {
        if ListExpr::can_cast(syntax.kind()) {
            Some(ListExpr { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct MapExpr {
    pub(crate) syntax: SyntaxNode,
}

impl MapExpr {
    pub fn open_brace_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::OPEN_BRACE)
    }
    pub fn exprs(&self) -> AstChildren<Expr> {
        support::children(&self.syntax)
    }
    pub fn close_brace_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::CLOSE_BRACE)
    }
}

impl AstNode for MapExpr {
    type Language = ScarpetLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::MAP_EXPR
    }
    fn cast(syntax: SyntaxNode) -> Option<MapExpr> {
        if MapExpr::can_cast(syntax.kind()) {
            Some(MapExpr { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ParenExpr {
    pub(crate) syntax: SyntaxNode,
}

impl ParenExpr {
    pub fn open_paren_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::OPEN_PAREN)
    }
    pub fn expr(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
    pub fn close_paren_token(&self) -> Option<SyntaxToken> {
        support::token(&self.syntax, SyntaxKind::CLOSE_PAREN)
    }
}

impl AstNode for ParenExpr {
    type Language = ScarpetLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::PAREN_EXPR
    }
    fn cast(syntax: SyntaxNode) -> Option<ParenExpr> {
        if ParenExpr::can_cast(syntax.kind()) {
            Some(ParenExpr { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct PrefixExpr {
    pub(crate) syntax: SyntaxNode,
}

impl PrefixExpr {
    pub fn expr(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
}

impl AstNode for PrefixExpr {
    type Language = ScarpetLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::PREFIX_EXPR
    }
    fn cast(syntax: SyntaxNode) -> Option<PrefixExpr> {
        if PrefixExpr::can_cast(syntax.kind()) {
            Some(PrefixExpr { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct BinExpr {
    pub(crate) syntax: SyntaxNode,
}

impl BinExpr {
    pub fn lhs(&self) -> Option<Expr> {
        support::children(&self.syntax).next()
    }
    pub fn rhs(&self) -> Option<Expr> {
        support::children(&self.syntax).nth(1)
    }
}

impl AstNode for BinExpr {
    type Language = ScarpetLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::BIN_EXPR
    }
    fn cast(syntax: SyntaxNode) -> Option<BinExpr> {
        if BinExpr::can_cast(syntax.kind()) {
            Some(BinExpr { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct CommaChain {
    pub(crate) syntax: SyntaxNode,
}

impl CommaChain {
    pub fn exprs(&self) -> AstChildren<Expr> {
        support::children(&self.syntax)
    }
}

impl AstNode for CommaChain {
    type Language = ScarpetLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::COMMA_CHAIN
    }
    fn cast(syntax: SyntaxNode) -> Option<CommaChain> {
        if CommaChain::can_cast(syntax.kind()) {
            Some(CommaChain { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct SemiChain {
    pub(crate) syntax: SyntaxNode,
}

impl SemiChain {
    pub fn exprs(&self) -> AstChildren<Expr> {
        support::children(&self.syntax)
    }
}

impl AstNode for SemiChain {
    type Language = ScarpetLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::SEMI_CHAIN
    }
    fn cast(syntax: SyntaxNode) -> Option<SemiChain> {
        if SemiChain::can_cast(syntax.kind()) {
            Some(SemiChain { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct EmptyArg {
    pub(crate) syntax: SyntaxNode,
}

impl EmptyArg {
    pub fn expr(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
}

impl AstNode for EmptyArg {
    type Language = ScarpetLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SyntaxKind::EMPTY_ARG
    }
    fn cast(syntax: SyntaxNode) -> Option<EmptyArg> {
        if EmptyArg::can_cast(syntax.kind()) {
            Some(EmptyArg { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Expr {
    Literal(Literal),
    NameRef(NameRef),
    CallExpr(CallExpr),
    ListExpr(ListExpr),
    MapExpr(MapExpr),
    ParenExpr(ParenExpr),
    PrefixExpr(PrefixExpr),
    BinExpr(BinExpr),
    CommaChain(CommaChain),
    SemiChain(SemiChain),
    EmptyArg(EmptyArg),
}

impl AstNode for Expr {
    type Language = ScarpetLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(
            kind,
            SyntaxKind::LITERAL
                | SyntaxKind::NAME_REF
                | SyntaxKind::CALL_EXPR
                | SyntaxKind::LIST_EXPR
                | SyntaxKind::MAP_EXPR
                | SyntaxKind::PAREN_EXPR
                | SyntaxKind::PREFIX_EXPR
                | SyntaxKind::BIN_EXPR
                | SyntaxKind::COMMA_CHAIN
                | SyntaxKind::SEMI_CHAIN
                | SyntaxKind::EMPTY_ARG
        )
    }
    fn cast(syntax: SyntaxNode) -> Option<Expr> {
        let res = match syntax.kind() {
            SyntaxKind::LITERAL => Expr::Literal(Literal { syntax }),
            SyntaxKind::NAME_REF => Expr::NameRef(NameRef { syntax }),
            SyntaxKind::CALL_EXPR => Expr::CallExpr(CallExpr { syntax }),
            SyntaxKind::LIST_EXPR => Expr::ListExpr(ListExpr { syntax }),
            SyntaxKind::MAP_EXPR => Expr::MapExpr(MapExpr { syntax }),
            SyntaxKind::PAREN_EXPR => Expr::ParenExpr(ParenExpr { syntax }),
            SyntaxKind::PREFIX_EXPR => Expr::PrefixExpr(PrefixExpr { syntax }),
            SyntaxKind::BIN_EXPR => Expr::BinExpr(BinExpr { syntax }),
            SyntaxKind::COMMA_CHAIN => Expr::CommaChain(CommaChain { syntax }),
            SyntaxKind::SEMI_CHAIN => Expr::SemiChain(SemiChain { syntax }),
            SyntaxKind::EMPTY_ARG => Expr::EmptyArg(EmptyArg { syntax }),
            _ => return None,
        };
        Some(res)
    }
    fn syntax(&self) -> &SyntaxNode {
        match self {
            Expr::Literal(it) => &it.syntax,
            Expr::NameRef(it) => &it.syntax,
            Expr::CallExpr(it) => &it.syntax,
            Expr::ListExpr(it) => &it.syntax,
            Expr::MapExpr(it) => &it.syntax,
            Expr::ParenExpr(it) => &it.syntax,
            Expr::PrefixExpr(it) => &it.syntax,
            Expr::BinExpr(it) => &it.syntax,
            Expr::CommaChain(it) => &it.syntax,
            Expr::SemiChain(it) => &it.syntax,
            Expr::EmptyArg(it) => &it.syntax,
        }
    }
}

impl From<Literal> for Expr {
    fn from(node: Literal) -> Expr {
        Expr::Literal(node)
    }
}

impl From<NameRef> for Expr {
    fn from(node: NameRef) -> Expr {
        Expr::NameRef(node)
    }
}

impl From<CallExpr> for Expr {
    fn from(node: CallExpr) -> Expr {
        Expr::CallExpr(node)
    }
}

impl From<ListExpr> for Expr {
    fn from(node: ListExpr) -> Expr {
        Expr::ListExpr(node)
    }
}

impl From<MapExpr> for Expr {
    fn from(node: MapExpr) -> Expr {
        Expr::MapExpr(node)
    }
}

impl From<ParenExpr> for Expr {
    fn from(node: ParenExpr) -> Expr {
        Expr::ParenExpr(node)
    }
}

impl From<PrefixExpr> for Expr {
    fn from(node: PrefixExpr) -> Expr {
        Expr::PrefixExpr(node)
    }
}

impl From<BinExpr> for Expr {
    fn from(node: BinExpr) -> Expr {
        Expr::BinExpr(node)
    }
}

impl From<CommaChain> for Expr {
    fn from(node: CommaChain) -> Expr {
        Expr::CommaChain(node)
    }
}

impl From<SemiChain> for Expr {
    fn from(node: SemiChain) -> Expr {
        Expr::SemiChain(node)
    }
}

impl From<EmptyArg> for Expr {
    fn from(node: EmptyArg) -> Expr {
        Expr::EmptyArg(node)
    }
}
